#ifndef		__MT_ENUM_H
#define		__MT_ENUM_H

//error code
enum mteError
{
	MTE_ERROR_PACKET_HEADER					= -10,
	MTE_ERROR_SUB_PACKET_HEADER				= -9,
	MTE_ERROR_NO_DATA_RECEIVED				= -8,
	MTE_ERROR_UN_COMPLETED_PACKET_RECV		= -7,
	MTE_ERROR_UN_COMPLETED_PACKET_SEND		= -6,
	MTE_ERROR_DATA_RECEIVED					= -5,
	MTE_ERROR_DATA_SEND						= -4,
	MTE_ERROR_DB_SQL_EXEC_DIRECT			= -3,
	MTE_ERROR_DB_QUERY_NO_DATA				= -2,
	MTE_ERROR_DB_ESTMT_OUT_RANGE			= -1,
	MTE_ERROR								= 0,
	MTE_ERROR_OK							= 1
};

#endif	/// __MT_ENUM_H
